use std::collections::BTreeSet;
use std::fs;
use std::path::PathBuf;

use anyhow::{bail, Context, Result};
use serde::{Deserialize, Serialize};

use crate::{aliases, exec, output};

#[derive(Debug, Default, Deserialize, Serialize)]
struct LiveIntent {
    schema: String,
    hostname: String,
    packages: BTreeSet<String>,
}

pub fn install(packages: &[String], dry_run: bool) -> Result<()> {
    require_packages(packages)?;
    let mut intent = load()?;
    for package in packages {
        intent
            .packages
            .insert(aliases::nixpkgs_attr(package).to_string());
    }
    if dry_run {
        output::dry_run(&format!(
            "would record {} in the live machine profile",
            packages.join(", ")
        ));
        return Ok(());
    }
    reconcile(&intent)?;
    save(&intent)
}

pub fn remove(packages: &[String], dry_run: bool) -> Result<()> {
    require_packages(packages)?;
    let mut intent = load()?;
    for package in packages {
        intent.packages.remove(aliases::nixpkgs_attr(package));
    }
    if dry_run {
        output::dry_run(&format!(
            "would remove {} from the live machine profile",
            packages.join(", ")
        ));
        return Ok(());
    }
    reconcile(&intent)?;
    save(&intent)
}

pub fn polymerize(dry_run: bool) -> Result<()> {
    let intent = load()?;
    if dry_run {
        output::dry_run(&format!(
            "would polymerize {} live packages",
            intent.packages.len()
        ));
        return Ok(());
    }
    reconcile(&intent)
}

fn reconcile(intent: &LiveIntent) -> Result<()> {
    let profile = profile_path()?;
    if let Some(parent) = profile.parent() {
        fs::create_dir_all(parent)?;
    }
    let installables: Vec<String> = intent
        .packages
        .iter()
        .map(|p| format!("nixpkgs#{p}"))
        .collect();
    output::status(&format!(
        "polymerizing {} live packages...",
        installables.len()
    ));
    exec::nix_profile_reconcile(&profile, &installables)?;
    ensure_path_integration(&profile)
}

fn ensure_path_integration(profile: &std::path::Path) -> Result<()> {
    let home = dirs::home_dir().context("could not determine home directory")?;
    let env_dir = home.join(".config/nex");
    fs::create_dir_all(&env_dir)?;
    let env_file = env_dir.join("env.sh");
    let profile_bin = profile.join("bin");
    let content = format!(
        "# Generated by nex. Source this file from a login shell.\n\
         case \":$PATH:\" in\n\
         \x20 *:\"{}\":*) ;;\n\
         \x20 *) export PATH=\"{}:$PATH\" ;;\n\
         esac\n",
        profile_bin.display(),
        profile_bin.display()
    );
    crate::edit::atomic_write_bytes(&env_file, content.as_bytes())?;

    let source_line = ". \"$HOME/.config/nex/env.sh\" # nex live profile";
    ensure_managed_source(&home.join(".profile"), source_line)?;

    let shell = std::env::var("SHELL").unwrap_or_default();
    if shell.ends_with("/zsh") {
        ensure_managed_source(&home.join(".zprofile"), source_line)?;
    }
    Ok(())
}

fn ensure_managed_source(path: &std::path::Path, source_line: &str) -> Result<()> {
    let mut content = if path.exists() {
        fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?
    } else {
        String::new()
    };
    if content.lines().any(|line| line.trim() == source_line) {
        return Ok(());
    }
    if !content.is_empty() && !content.ends_with('\n') {
        content.push('\n');
    }
    content.push_str(source_line);
    content.push('\n');
    crate::edit::atomic_write_bytes(path, content.as_bytes())
}

fn load() -> Result<LiveIntent> {
    let path = intent_path()?;
    if path.exists() {
        return toml::from_str(&fs::read_to_string(&path)?).context("invalid live machine profile");
    }
    Ok(LiveIntent {
        schema: "io.styrene.nex.live-profile.v1".into(),
        hostname: hostname()?,
        packages: BTreeSet::new(),
    })
}

fn save(intent: &LiveIntent) -> Result<()> {
    let path = intent_path()?;
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    crate::edit::atomic_write_bytes(&path, toml::to_string_pretty(intent)?.as_bytes())
}

fn machine_dir() -> Result<PathBuf> {
    let root = std::env::var_os("NEX_STATE_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| {
            dirs::state_dir()
                .unwrap_or_else(|| dirs::home_dir().unwrap_or_default().join(".local/state"))
                .join("nex")
        });
    Ok(root.join("machines").join(hostname()?))
}
fn intent_path() -> Result<PathBuf> {
    Ok(machine_dir()?.join("live-profile.toml"))
}
fn profile_path() -> Result<PathBuf> {
    Ok(machine_dir()?.join("profile"))
}
fn hostname() -> Result<String> {
    crate::discover::hostname().context("could not determine hostname")
}
fn require_packages(packages: &[String]) -> Result<()> {
    if packages.is_empty() {
        bail!("no packages specified")
    } else {
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::ensure_managed_source;

    #[test]
    fn managed_shell_source_is_idempotent_and_preserves_content() {
        let dir = tempfile::tempdir().expect("temp dir");
        let profile = dir.path().join(".profile");
        std::fs::write(&profile, "export EXISTING=1\n").expect("fixture");
        let source = ". \"$HOME/.config/nex/env.sh\" # nex live profile";

        ensure_managed_source(&profile, source).expect("first integration");
        ensure_managed_source(&profile, source).expect("second integration");

        let content = std::fs::read_to_string(profile).expect("read profile");
        assert!(content.starts_with("export EXISTING=1\n"));
        assert_eq!(content.matches(source).count(), 1);
    }
}
